# Generated by Django 5.2.12 on 2026-03-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('category', models.CharField(choices=[('Футболки', 'Футболки'), ('Худи', 'Худи'), ('Джинсы', 'Джинсы'), ('Куртки', 'Куртки'), ('Обувь', 'Обувь'), ('Рубашки', 'Рубашки'), ('Штаны', 'Штаны'), ('Свитшоты', 'Свитшоты')], max_length=50, verbose_name='Категория')),
                ('image', models.CharField(max_length=255, verbose_name='Путь к картинке')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
